# Generated by Django 2.0.4 on 2018-04-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
