# Generated by Django 2.0.4 on 2018-04-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='identifier',
            field=models.BigIntegerField(default=6432027986138306, primary_key=True, serialize=False, unique=True, verbose_name='identifier'),
        ),
    ]
