# Generated by Django 2.0.4 on 2018-04-20 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20180420_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='registered_since',
            field=models.DateField(default=datetime.date(2018, 4, 20), verbose_name='Registerd since'),
        ),
    ]
