# Generated by Django 2.0.4 on 2018-04-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20180423_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='identifier',
            field=models.BigIntegerField(default=6433996507100450, primary_key=True, serialize=False, unique=True, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='human',
            name='password',
            field=models.CharField(max_length=200, verbose_name='password'),
        ),
    ]
