# Generated by Django 2.0.4 on 2018-04-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20180423_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='identifier',
            field=models.BigIntegerField(default=6433998159997864, primary_key=True, serialize=False, unique=True, verbose_name='identifier'),
        ),
    ]
