# Generated by Django 2.0.4 on 2018-04-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20180423_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='identifier',
            field=models.BigIntegerField(default=6434066505028677, primary_key=True, serialize=False, unique=True, verbose_name='identifier'),
        ),
    ]
