# Generated by Django 2.0.4 on 2018-04-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_auto_20180423_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='identifier',
            field=models.BigIntegerField(default=6434075668155499, primary_key=True, serialize=False,
                                         unique=True, verbose_name='identifier'),
        ),
    ]
