# Generated by Django 2.0.4 on 2018-04-27 21:33

import datetime
from django.db import migrations, models
import modo.util.auxiliary


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_auto_20180423_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='identifier',
            field=models.BigIntegerField(default=modo.util.auxiliary.make_id, primary_key=True, serialize=False, unique=True, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='human',
            name='registered_since',
            field=models.DateField(default=datetime.date.today, verbose_name='registerd since'),
        ),
    ]
