# Generated by Django 2.0.4 on 2018-04-24 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_auto_20180423_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='registered_since',
            field=models.DateField(default=datetime.date.today, verbose_name='registerd since'),
        ),
    ]
