# Generated by Django 2.0.4 on 2018-04-29 06:04

from django.conf import settings
from django.db import migrations, models
import modo.util.auxiliary


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('identifier', models.BigIntegerField(default=modo.util.auxiliary.make_id, primary_key=True, serialize=False, unique=True, verbose_name='identifier')),
                ('url', models.TextField(unique=True, verbose_name='url')),
                ('title', models.TextField(null=True, verbose_name='title')),
                ('authors', models.TextField(null=True, verbose_name='authors')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='language')),
                ('text', models.TextField(null=True, verbose_name='text')),
                ('site_name', models.CharField(max_length=50, null=True, verbose_name='site name')),
                ('tweets', models.TextField(null=True, verbose_name='tweets')),
                ('publish_time', models.DateTimeField(null=True, verbose_name='publish time')),
                ('videos', models.TextField(null=True, verbose_name='videos')),
                ('tags', models.TextField(null=True, verbose_name='tags')),
                ('saved_by', models.ManyToManyField(related_name='saved', to=settings.AUTH_USER_MODEL)),
                ('shared_by', models.ManyToManyField(related_name='shared', to=settings.AUTH_USER_MODEL)),
                ('viewed_by', models.ManyToManyField(related_name='viewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
