# Generated by Django 2.0.4 on 2018-05-03 06:43

from django.db import migrations, models
import modo.util.auxiliary


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('identifier', models.BigIntegerField(default=modo.util.auxiliary.make_id, primary_key=True, serialize=False, unique=True, verbose_name='identifier')),
                ('url', models.TextField(unique=True, verbose_name='url')),
                ('title', models.TextField(verbose_name='title')),
                ('authors', models.TextField(null=True, verbose_name='authors')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='language')),
                ('text', models.TextField(null=True, verbose_name='text')),
                ('site_name', models.CharField(max_length=50, null=True, verbose_name='site name')),
                ('tweets', models.TextField(null=True, verbose_name='tweets')),
                ('publish_time', models.DateTimeField(null=True, verbose_name='publish time')),
                ('videos', models.TextField(null=True, verbose_name='videos')),
                ('tags', models.TextField(null=True, verbose_name='tags')),
                ('topic', models.CharField(default='general', max_length=20, verbose_name='category')),
                ('images', models.TextField(null=True, verbose_name='images')),
                ('views', models.IntegerField(default=0, verbose_name='views')),
            ],
            options={
                'ordering': ['-publish_time', 'views'],
            },
        ),
    ]
