# Generated by Django 2.0.4 on 2018-04-27 21:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modo.util.auxiliary


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_on', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.TextField(null=True, verbose_name='authors'),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='article',
            name='identifier',
            field=models.BigIntegerField(default=modo.util.auxiliary.make_id, primary_key=True, serialize=False, unique=True, verbose_name='identifier'),
        ),
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(default='en', max_length=10, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_time',
            field=models.DateTimeField(null=True, verbose_name='publish time'),
        ),
        migrations.AddField(
            model_name='article',
            name='site_name',
            field=models.CharField(max_length=50, null=True, verbose_name='site name'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.TextField(null=True, verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.TextField(null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='tweets',
            field=models.TextField(null=True, verbose_name='tweets'),
        ),
        migrations.AddField(
            model_name='article',
            name='videos',
            field=models.TextField(null=True, verbose_name='videos'),
        ),
        migrations.AddField(
            model_name='readership',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Article'),
        ),
        migrations.AddField(
            model_name='readership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='saved_by',
            field=models.ManyToManyField(through='news.Readership', to=settings.AUTH_USER_MODEL),
        ),
    ]
