# Generated by Django 2.0.5 on 2018-05-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180504_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='domain',
            field=models.CharField(default='google.com', max_length=50, verbose_name='domain'),
        ),
    ]
