# Generated by Django 2.0.4 on 2018-05-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180503_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.TextField(blank=True, null=True, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tweets',
            field=models.TextField(blank=True, null=True, verbose_name='tweets'),
        ),
        migrations.AlterField(
            model_name='article',
            name='videos',
            field=models.TextField(blank=True, null=True, verbose_name='videos'),
        ),
    ]
