# Generated by Django 2.0.4 on 2018-05-03 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180503_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='shared_by',
            field=models.ManyToManyField(blank=True, related_name='shared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
