# Generated by Django 2.0.4 on 2018-05-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180503_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, verbose_name='slug title'),
        ),
    ]
